'use client';
import { ReactNode, useEffect, useState } from 'react';
import './globals.css';
import { Rubik } from 'next/font/google';
import { useRouter, usePathname } from 'next/navigation';

const rubik = Rubik({ subsets: ['latin'] });

const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: ReactNode | any;
}

export default function RootLayout({ children }: RootLayoutProps) {
	const navigate = useRouter();
	const pathName = usePathname();
	const [token, setToken] = useState<any>('');

	useEffect(() => {
		const storedToken = localStorage.getItem('token');

		!storedToken && pathName !== '/'
			? navigate.push('/')
			: setToken(storedToken);
	}, [navigate, pathName]);

	return (
		<html lang='en'>
			<body className={rubik.className}>
				{pathName === '/' || token ? children : null}
			</body>
		</html>
	);
}
