'use client';
import { ReactNode, useEffect } from 'react';
import './globals.css';
import { Rubik } from 'next/font/google';
import { useRouter } from 'next/navigation';

const rubik = Rubik({ subsets: ['latin'] });

const metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

interface RootLayoutProps {
	children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
	const navigate = useRouter();

	useEffect(() => {
		const token = localStorage.getItem('token');
		if (!token) {
			navigate.push('/');
		}
	});

	return (
		<html lang='en'>
			<body className={rubik.className}>{children}</body>
		</html>
	);
}
